### ISSUE TITLE
Tests Fails

### ISSUE THREAD

**Issue by dcojan** [Seagate/kinetic-java#22]
Hi, 

My team and I can't get the simulator to work properly.
We are working on OSX 10.10.3
maven 3.3.3
java 1.8.0_45

Installation works fine but tests are failing as shown here :

```
===============================================
    GRP-simulator
    Tests run: 371, Failures: 13, Skips: 0
===============================================

[TestNG] Time taken by [FailedReporter passed=0 failed=0 skipped=0]: 51 ms
[TestNG] Time taken by org.testng.reporters.JUnitReportReporter@77afea7d: 60 ms
[TestNG] Time taken by org.testng.reporters.EmailableReporter2@6d86b085: 34 ms
[TestNG] Time taken by org.testng.reporters.jq.Main@299a06ac: 246 ms
[TestNG] Time taken by org.testng.reporters.XMLReporter@4ac68d3e: 140 ms
[TestNG] Time taken by org.testng.reporters.SuiteHTMLReporter@1f89ab83: 297 ms
Tests run: 371, Failures: 13, Errors: 0, Skipped: 0, Time elapsed: 49.749 sec <<< FAILURE! - in TestSuite
getLogNewAPI(com.seagate.kinetic.adminAPI.KineticAdminTest)  Time elapsed: 0.037 sec  <<< FAILURE!
java.lang.AssertionError: getLog throw exception: Kinetic Command Exception: INVALID_REQUEST: java.lang.NumberFormatException: For input string: ",11"
	at org.testng.Assert.fail(Assert.java:94)
	at com.seagate.kinetic.adminAPI.KineticAdminTest.getLogNewAPI(KineticAdminTest.java:2278)

testGetCapacityAndUtilization(com.seagate.kinetic.adminAPI.KineticAdminTest)  Time elapsed: 0.006 sec  <<< FAILURE!
java.lang.AssertionError: getLog throw exception: Kinetic Command Exception: INVALID_REQUEST: java.lang.NumberFormatException: For input string: ",38"
	at org.testng.Assert.fail(Assert.java:94)
	at com.seagate.kinetic.adminAPI.KineticAdminTest.testGetCapacityAndUtilization(KineticAdminTest.java:2707)

testGetTemperatureAndCapacityAndUtilization(com.seagate.kinetic.adminAPI.KineticAdminTest)  Time elapsed: 0.018 sec  <<< FAILURE!
java.lang.AssertionError: getLog throw exception: Kinetic Command Exception: INVALID_REQUEST: java.lang.NumberFormatException: For input string: ",53"
	at org.testng.Assert.fail(Assert.java:94)
	at com.seagate.kinetic.adminAPI.KineticAdminTest.testGetTemperatureAndCapacityAndUtilization(KineticAdminTest.java:2533)

testGetTemperatureAndUtilization(com.seagate.kinetic.adminAPI.KineticAdminTest)  Time elapsed: 0.002 sec  <<< FAILURE!
java.lang.AssertionError: getLog throw exception: Kinetic Command Exception: INVALID_REQUEST: java.lang.NumberFormatException: For input string: ",55"
	at org.testng.Assert.fail(Assert.java:94)
	at com.seagate.kinetic.adminAPI.KineticAdminTest.testGetTemperatureAndUtilization(KineticAdminTest.java:2664)

testGetUtilization(com.seagate.kinetic.adminAPI.KineticAdminTest)  Time elapsed: 0.004 sec  <<< FAILURE!
java.lang.AssertionError: getLog throw exception: Kinetic Command Exception: INVALID_REQUEST: java.lang.NumberFormatException: For input string: ",62"
	at org.testng.Assert.fail(Assert.java:94)
	at com.seagate.kinetic.adminAPI.KineticAdminTest.testGetUtilization(KineticAdminTest.java:2399)

testLockDevice_withIncorrectLockpin(com.seagate.kinetic.adminAPI.KineticAdminTest)  Time elapsed: 0.016 sec  <<< FAILURE!
java.lang.AssertionError: get log with unlocked device throw exception: Kinetic Command Exception: INVALID_REQUEST: java.lang.NumberFormatException: For input string: ",87"
	at org.testng.Assert.fail(Assert.java:94)
	at com.seagate.kinetic.adminAPI.KineticAdminTest.testLockDevice_withIncorrectLockpin(KineticAdminTest.java:2076)

testSetSecurity_modifyLockPin(com.seagate.kinetic.adminAPI.KineticAdminTest)  Time elapsed: 0 sec  <<< FAILURE!
java.lang.AssertionError: Change lock pin throw exceptionKinetic Command Exception: NOT_AUTHORIZED: Invalid old lock pin: <ByteString@65264e3c size=0>
	at org.testng.Assert.fail(Assert.java:94)
	at com.seagate.kinetic.adminAPI.KineticAdminTest.testSetSecurity_modifyLockPin(KineticAdminTest.java:1876)

testSetSecurity_setLockPin(com.seagate.kinetic.adminAPI.KineticAdminTest)  Time elapsed: 0.006 sec  <<< FAILURE!
java.lang.AssertionError: Set erase pin throw exceptionKinetic Command Exception: NOT_AUTHORIZED: Invalid old lock pin: <ByteString@65264e3c size=0>
	at org.testng.Assert.fail(Assert.java:94)
	at com.seagate.kinetic.adminAPI.KineticAdminTest.testSetSecurity_setLockPin(KineticAdminTest.java:1852)

test_GetLogTest(com.seagate.kinetic.adminAPI.KineticAdminTest)  Time elapsed: 0.006 sec  <<< FAILURE!
java.lang.AssertionError: getLog throw exception: Kinetic Command Exception: INVALID_REQUEST: java.lang.NumberFormatException: For input string: ",38"
	at org.testng.Assert.fail(Assert.java:94)
	at com.seagate.kinetic.adminAPI.KineticAdminTest.test_GetLogTest(KineticAdminTest.java:347)

testunLockDevice_withCorrectLockpin(com.seagate.kinetic.adminAPI.KineticAdminTest)  Time elapsed: 0.022 sec  <<< FAILURE!
java.lang.AssertionError: get log with unlock device throw exception: Kinetic Command Exception: INVALID_REQUEST: java.lang.NumberFormatException: For input string: ",85"
	at org.testng.Assert.fail(Assert.java:94)
	at com.seagate.kinetic.adminAPI.KineticAdminTest.testunLockDevice_withCorrectLockpin(KineticAdminTest.java:2155)

testLockDevice_withEmptyLockPin_LockDisable(com.seagate.kinetic.simulator.client.admin.impl.PinOpTest)  Time elapsed: 0.242 sec  <<< FAILURE!
java.lang.AssertionError: Lock disable, op throw exception: Kinetic Command Exception: INVALID_REQUEST: java.lang.NumberFormatException: For input string: ",74"
	at org.testng.Assert.fail(Assert.java:94)
	at com.seagate.kinetic.simulator.client.admin.impl.PinOpTest.testLockDevice_withEmptyLockPin_LockDisable(PinOpTest.java:135)

testLockDevice_withNullLockPin_LockDisable(com.seagate.kinetic.simulator.client.admin.impl.PinOpTest)  Time elapsed: 0.271 sec  <<< FAILURE!
java.lang.AssertionError: Lock disable, op throw exception: Kinetic Command Exception: INVALID_REQUEST: java.lang.NumberFormatException: For input string: ",35"
	at org.testng.Assert.fail(Assert.java:94)
	at com.seagate.kinetic.simulator.client.admin.impl.PinOpTest.testLockDevice_withNullLockPin_LockDisable(PinOpTest.java:111)

testLockDevice_withUnNullOrEmptyLockPin_LockEnable_unLockDevice(com.seagate.kinetic.simulator.client.admin.impl.PinOpTest)  Time elapsed: 0.244 sec  <<< FAILURE!
java.lang.AssertionError: After unlock device, op throw exception: Kinetic Command Exception: INVALID_REQUEST: java.lang.NumberFormatException: For input string: ",80"
	at org.testng.Assert.fail(Assert.java:94)
	at com.seagate.kinetic.simulator.client.admin.impl.PinOpTest.testLockDevice_withUnNullOrEmptyLockPin_LockEnable_unLockDevice(PinOpTest.java:81)


Results :

Failed tests:
  KineticAdminTest.getLogNewAPI:2278 getLog throw exception: Kinetic Command Exception: INVALID_REQUEST: java.lang.NumberFormatException: For input string: ",11"
  KineticAdminTest.testGetCapacityAndUtilization:2707 getLog throw exception: Kinetic Command Exception: INVALID_REQUEST: java.lang.NumberFormatException: For input string: ",38"
  KineticAdminTest.testGetTemperatureAndCapacityAndUtilization:2533 getLog throw exception: Kinetic Command Exception: INVALID_REQUEST: java.lang.NumberFormatException: For input string: ",53"
  KineticAdminTest.testGetTemperatureAndUtilization:2664 getLog throw exception: Kinetic Command Exception: INVALID_REQUEST: java.lang.NumberFormatException: For input string: ",55"
  KineticAdminTest.testGetUtilization:2399 getLog throw exception: Kinetic Command Exception: INVALID_REQUEST: java.lang.NumberFormatException: For input string: ",62"
  KineticAdminTest.testLockDevice_withIncorrectLockpin:2076 get log with unlocked device throw exception: Kinetic Command Exception: INVALID_REQUEST: java.lang.NumberFormatException: For input string: ",87"
  KineticAdminTest.testSetSecurity_modifyLockPin:1876 Change lock pin throw exceptionKinetic Command Exception: NOT_AUTHORIZED: Invalid old lock pin: <ByteString@65264e3c size=0>
  KineticAdminTest.testSetSecurity_setLockPin:1852 Set erase pin throw exceptionKinetic Command Exception: NOT_AUTHORIZED: Invalid old lock pin: <ByteString@65264e3c size=0>
  KineticAdminTest.test_GetLogTest:347 getLog throw exception: Kinetic Command Exception: INVALID_REQUEST: java.lang.NumberFormatException: For input string: ",38"
  KineticAdminTest.testunLockDevice_withCorrectLockpin:2155 get log with unlock device throw exception: Kinetic Command Exception: INVALID_REQUEST: java.lang.NumberFormatException: For input string: ",85"
  PinOpTest.testLockDevice_withEmptyLockPin_LockDisable:135 Lock disable, op throw exception: Kinetic Command Exception: INVALID_REQUEST: java.lang.NumberFormatException: For input string: ",74"
  PinOpTest.testLockDevice_withNullLockPin_LockDisable:111 Lock disable, op throw exception: Kinetic Command Exception: INVALID_REQUEST: java.lang.NumberFormatException: For input string: ",35"
  PinOpTest.testLockDevice_withUnNullOrEmptyLockPin_LockEnable_unLockDevice:81 After unlock device, op throw exception: Kinetic Command Exception: INVALID_REQUEST: java.lang.NumberFormatException: For input string: ",80"

Tests run: 371, Failures: 13, Errors: 0, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] Kinetic ............................................ SUCCESS [  0.732 s]
[INFO] Kinetic/Common ..................................... SUCCESS [  6.513 s]
[INFO] Kinetic/Client ..................................... SUCCESS [  1.610 s]
[INFO] Kinetic/Simulator .................................. SUCCESS [  1.176 s]
[INFO] Kinetic/Test ....................................... FAILURE [ 55.100 s]
[INFO] Kinetic/All-in-one ................................. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:05 min
[INFO] Finished at: 2015-07-15T10:20:08+02:00
[INFO] Final Memory: 27M/377M
[INFO] ------------------------------------------------------------------------
```

typical response from the simulator is :
```
juil. 15, 2015 10:11:27 AM com.seagate.kinetic.simulator.internal.SimulatorEngine processRequest
AVERTISSEMENT: java.lang.NumberFormatException: For input string: ",24"
com.seagate.kinetic.simulator.internal.handler.ServiceException: java.lang.NumberFormatException: For input string: ",24"
	at com.seagate.kinetic.simulator.internal.handler.GetLogOpHandler.processRequest(GetLogOpHandler.java:44)
	at com.seagate.kinetic.simulator.internal.RequestContext.processRequest(RequestContext.java:265)
	at com.seagate.kinetic.simulator.internal.SimulatorEngine.processRequest(SimulatorEngine.java:463)
	at com.seagate.kinetic.simulator.io.provider.nio.NioQueuedRequestProcessRunner.doProcessMessage(NioQueuedRequestProcessRunner.java:191)
	at com.seagate.kinetic.simulator.io.provider.nio.NioQueuedRequestProcessRunner.run(NioQueuedRequestProcessRunner.java:137)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NumberFormatException: For input string: ",24"
	at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2043)
	at sun.misc.FloatingDecimal.parseDouble(FloatingDecimal.java:110)
	at java.lang.Double.parseDouble(Double.java:538)
	at com.seagate.kinetic.simulator.utility.UtilizationGenerator.generateValue(UtilizationUtil.java:73)
	at com.seagate.kinetic.simulator.utility.UtilizationGenerator.generate(UtilizationUtil.java:52)
	at com.seagate.kinetic.simulator.utility.UtilizationUtil.getUtilization(UtilizationUtil.java:39)
	at com.seagate.kinetic.simulator.internal.GetLogHandler.handleGetLog(GetLogHandler.java:116)
	at com.seagate.kinetic.simulator.internal.handler.GetLogOpHandler.processRequest(GetLogOpHandler.java:42)
	... 7 more
```
Are we missing something ?

Thank you for your time.

**Comment by chenchongli** [comment]
Damien,

Thanks for your reporting.

I couldn't reproduce the issue in my environment(mac os x 10.9.5, maven 3.3.3, java 1.8.0_51). However, according to your detail trace, I have refactored one method named generateValue in class of UtilizationUtil to avoid NumberFormatException. The code url is the following:
https://github.com/Seagate/kinetic-java/commit/a634806af3ee4774ac5d80ca74b6ce526d471489

Please update the latest kinetic-java source code and try it again. At the same time, removing default Kinetic_Home directory manually should be helpful to clean your local environment before compiling. The command line is "rm -rf ~/kinetic" .

Hope this helps and feel free to let us know the result please.

Sincerely
Emma

**Comment by dcojan** [comment]
Hello and thank you !

All tests now passes and kineticstat in kinetic-cpp-example, which used to fail systematicaly, now runs fine. We're still having connection issues, I didn't mention that before because this may need it's own issue report.

Cordially

Damien
