### ISSUE TITLE
Connection Invalid magic number

### ISSUE THREAD

**Issue by QuentinPerez** [Seagate/kinetic-java#23]
Hello,

We are working on kinetic and when we try to connect with the simulator, we have some errors.

Darwin Kernel Version 14.3.0
maven: 3.2.5
java version "1.8.0_45"

```
WARNING: Unexpected exception from downstream.
io.netty.handler.codec.CorruptedFrameException: Invalid magic number: 22
	at com.seagate.kinetic.common.protocol.codec.KineticDecoder.decode(KineticDecoder.java:85)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:228)
	at io.netty.handler.codec.ByteToMessageDecoder.channelInactive(ByteToMessageDecoder.java:192)
	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelInactive(DefaultChannelHandlerContext.java:240)
	at io.netty.channel.DefaultChannelHandlerContext.fireChannelInactive(DefaultChannelHandlerContext.java:226)
	at io.netty.channel.DefaultChannelPipeline.fireChannelInactive(DefaultChannelPipeline.java:767)
	at io.netty.channel.AbstractChannel$AbstractUnsafe$5.run(AbstractChannel.java:567)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:354)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:353)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:101)
	at java.lang.Thread.run(Thread.java:745)
```

The code to connect with the simulator,

```
  kinetic::KineticConnectionFactory kinetic_connection_factory = kinetic::NewKineticConnectionFactory();
  kinetic::ConnectionOptions options;
  std::unique_ptr<kinetic::NonblockingKineticConnection> connection;

  options.host = "127.0.0.1";
  options.port = 8123;
  options.user_id = 1;
  options.hmac_key = "asdfasdf";


  kinetic::Status status = kinetic_connection_factory.NewNonblockingConnection(options, connection);
  if (!status.ok()) {
      printf("FAILED\n");
  } else {
      printf("SUCCEED\n");
  }
```

And it's completely random sometimes it's works, sometimes not.

Thanks for your time.

**Comment by QuentinPerez** [comment]
It was a ssl problem.
